### ISSUE TITLE
Types are wrong

### ISSUE THREAD

**Issue by preslavsh** [nucleus-sh/nucleus-nodejs#2]
It appears that the types are looking like the old electron version

As example types are missing the  `appStarted` method.

Also types are compilable

![error](https://user-images.githubusercontent.com/6237138/72206778-85a4cf00-349a-11ea-933b-6327331c8f18.PNG)

**Comment by vincelwt** [comment]
Thanks for reporting! Should be fixed with 3.0.2 :)
